### ISSUE TITLE
Add a web UI to Casbin-Server, so admins can manage the Casbin instances via the UI

### ISSUE THREAD

**Issue by hsluoyz** [casbin/issues#5]
You can refer to the code here: https://github.com/casbin/web-ui

The pictures are shown in: https://github.com/casbin/casbin#policy-management

**Comment by Ishaan28malik** [comment]
You mean adding login gateway for the Casbin Dashboard right? or if you wanted to implement just the UI then this issue can be closed?
@hsluoyz

**Comment by hsluoyz** [comment]
Casbin Dashboard is the solution for this issue.
